### ISSUE TITLE
Please update pubspec.yaml

### ISSUE THREAD

**Issue by bp74** [realbluesky/StageXL_RichTextField#3]
Hi,

There is a new version of StageXL with version 0.11.0. The version constraint in your pubspec.yaml limits the version to <0.11.0. It would be great if you could update the constraint.

Thanks a lot,
Bernhard

**Comment by alexgann** [comment]
Done and done.  Thanks for reaching out.  I didn't test though - so if you can verify it still works that'd be great.  The project that needed DartVN (which needed this library) was abandoned, so I haven't been in Dart much at all these past few months.  Bit bummed on the Dart announcement today...

**Comment by bp74** [comment]
Thanks for the quick update. I did a test and it works fine! It would be great if you could also update the version of stagexl_richtextfield and upload it to Pub.

Regarding the announcement, yes it's a little bit sad but i the dart2js compiler works pretty good and i hope they can improve it even more. Dart is still a great language - i know it because i have to write a lot of TypeScript at work and i hate it :)
